# Generated by Django 3.1 on 2020-08-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pp_autologon_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(max_length=15, unique=True)),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_mail', models.EmailField(max_length=50)),
            ],
        ),
    ]
