# Generated by Django 2.2 on 2020-11-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=64)),
                ('article_detail', models.CharField(max_length=1000)),
            ],
        ),
    ]
